### ISSUE TITLE
homework A

### ISSUE THREAD

**Issue by iliadmitriev** [avoevodin/brigadier#2]
* create new app project
* add models Project, Tasks
* setup admin (projects, tasks, employees)
* generate some data
* tranlation (en, ru)
* setup List, Detail, CrUD (create, Update, delete) operations for (projects, tasks, employees)
* bootstrap design, [bootstrap icons](https://icons.getbootstrap.com) (for buttons)
* usability (back urls in every template, edit, delete, cancel buttons) 
* write README docs
* tests

**Comment by avoevodin** [comment]
Closed without tests. It'll be done in the separated issue.
